# Generated by Django 6.0.2 on 2026-02-27 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('tx_type', models.CharField(db_index=True, max_length=32)),
                ('description', models.TextField()),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('units', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['stock_symbol'], name='dashboard_t_stock_s_ca6079_idx'), models.Index(fields=['tx_type'], name='dashboard_t_tx_type_6a9998_idx'), models.Index(fields=['date'], name='dashboard_t_date_251968_idx')],
            },
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('account', models.CharField(db_index=True, max_length=128)),
                ('debit', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('description', models.TextField()),
                ('line_no', models.PositiveIntegerField()),
                ('tx_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.transactions')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='dashboard_j_date_489105_idx'), models.Index(fields=['account'], name='dashboard_j_account_03817f_idx')],
                'unique_together': {('date', 'account', 'debit', 'credit', 'description', 'tx_id')},
            },
        ),
    ]
