# Generated by Django 6.0.2 on 2026-02-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journals',
            new_name='Journal',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.RenameIndex(
            model_name='journal',
            new_name='dashboard_j_date_4d0981_idx',
            old_name='dashboard_j_date_489105_idx',
        ),
        migrations.RenameIndex(
            model_name='journal',
            new_name='dashboard_j_account_583a45_idx',
            old_name='dashboard_j_account_03817f_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='dashboard_t_stock_s_f8f86b_idx',
            old_name='dashboard_t_stock_s_ca6079_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='dashboard_t_tx_type_88fd11_idx',
            old_name='dashboard_t_tx_type_6a9998_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='dashboard_t_date_e63f52_idx',
            old_name='dashboard_t_date_251968_idx',
        ),
    ]
