# Generated by Django 6.0.2 on 2026-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_journals_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='line_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
