# Generated by Django 6.0.2 on 2026-02-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_transaction_fx_rate_alter_journal_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='line_no',
        ),
    ]
